version: '3.2'

services:
   imagebuild:
     build: 
       context: .
       dockerfile: Dockerfile
       args:
         IMAGE_DISTRO: alpine
         IMAGE_VERSION: latest
     volumes:
       - ./output:/output
       - ./input:/input
